### ISSUE TITLE
Login Credentials Error Handling

### ISSUE THREAD

**Issue by FabiolaSaga** [Lambda-School-Labs/nutrition-tracker-ios-pt7#4]
There is no error handling to validate user credentials, users have no way of knowing if they entered the wrong credentials at login.

**Comment by dillonp23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile App - Login/Logout](https://trello.com/c/77WKHb5j/42-mobile-app-login-logout)

**Comment by dillonp23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile App - Sign up/Registration Bug Fixes](https://trello.com/c/eQHJLqNu/66-mobile-app-sign-up-registration-bug-fixes)
